engines:
  rubocop:
    enabled: true
    checks:
     Rubocop/Metrics/ClassLength:
       enabled: false
     Rubocop/Metrics/MethodLength:
       enabled: false
     Rubocop/Metrics/ModuleLength:
       enabled: false
     Rubocop/Metrics/BlockNesting:
       enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
